### ISSUE TITLE
Add handling of Top of page event

### ISSUE THREAD

**Issue by fidley** [fidley/falv#3]

**Comment by fidley** [comment]
Some build in headers would be nice, for example selection criteria. Or default template to put html header + some logo

**Comment by fidley** [comment]
Done for 7.40

**Comment by Buterbrott** [comment]
Why tables are not visible in header document?

**Comment by fidley** [comment]
Can you give me a snippet of the code?

**Comment by Buterbrott** [comment]
Just trying to change demo program ZDEMO_FALV02
`  method evf_top_of_page.

    e_dyndoc_id->add_text( text = 'Top Of Page' sap_style = cl_dd_area=>heading ).

    e_dyndoc_id->new_line( repeat = 1 ).

    e_dyndoc_id->add_table(
      EXPORTING
        no_of_columns               =     2
      IMPORTING
        tablearea                   =  DATA(lr_tarea)
    ).

   lr_tarea->add_text( text = '1' ).
   lr_tarea->add_text( text = '2' ).
   lr_tarea->new_row( ).
   lr_tarea->add_text( text = '3' ).
   lr_tarea->add_text( text = '4' ).

  endmethod.`

**Comment by Buterbrott** [comment]
Sorry, that was my fault.  Forgot to use merge_document

**Comment by fidley** [comment]
Sorry from my side, I haven't yet time to look on it..

**Comment by fidley** [comment]
Falv for 7.31 is in separate repository now.
