### ISSUE TITLE
Hotspots needs double click?

### ISSUE THREAD

**Issue by Bonzay0** [fidley/falv#36]
When using hotspot in salv or normal alv there is no need for the double click.
When using hotspot with falv a double click on the column is needed.

Why there's a different behavior? is it fixable?

**Comment by fidley** [comment]
Can you tell me which version do you have? 7.31 or 7.40 ? I remmember that I had such issue previously but now seems to be ok.

**Comment by Bonzay0** [comment]
I have the v740.1.0.11

**Comment by fidley** [comment]
Thanks, I'll check at home on current version if the problem still exists. There were some minor changes in v740.1.0.12.

**Comment by fidley** [comment]
Now I remember something... could you install newer version? This bug was connected to delayed events, they were registered directly while creating falv but they made this error that once you've clicked to hotspot then delayed cell selection event was raised and not hot spot.

**Comment by Bonzay0** [comment]
It still doesn't work, even in v740.1.0.12.

So it might yet to be resolved or I installed the nugget incorrectly.

**Comment by fidley** [comment]
I see it in the code which is in the nugget and abapGit. Methods create and create_by_copy. I will remove this in the evening.

![image](https://cloud.githubusercontent.com/assets/7912195/22293208/0a3e1612-e30f-11e6-9087-82020ec14b75.png)

**Comment by fidley** [comment]
solved with version 13
