### ISSUE TITLE
Falv Mass Replace bug: dump entering non-numeric chars to a numeric field

### ISSUE THREAD

**Issue by SantiMorenoSAP** [fidley/falv#38]
First of all thanks again for this greatly class.
I´ve found a bug in the Mass replace functionality.
If we have a numeric column, and we try to replace it with a non numeric character a dump is thrown.
The dump is originated in function Z_FALV_MASS_REPLACE, in the assigment of the Mass Replace field screen to the ALV tab:
<any> = <paramst>-low.

I think this line can be commented as there is a few lines later a call to an ALV method to do the assigment again.
io_grid->set_delta_cells

What do you think?

**Comment by fidley** [comment]
Hi Santi, 
thanks a lot for your input in version 7.31 !

Well you might be right. I'll do some tests and if they are succesfull then I'll update it. Or you already did the tests?
Cheers
Łukasz

**Comment by SantiMorenoSAP** [comment]
I did some test but It didnt work. Maybe an error management popup log
could be.

**Comment by fidley** [comment]
Ok Then I'll do some additional tests on my own and I'll come back to you. At the end we can check the type of field symbol <any> if is the same to the type of -low, but I'd like to avoid it as this could be time consuming if done wrong. Definitelly a buffer table for the RTTS type object would be needed for each column.
Then when types aren't the same I could omit passing -low value to <any> but still pass it o set_delta_cells.

Let's see.

**Comment by fidley** [comment]
Hello Santi, 
I've check the code and also I've test a lot and I couldn't repeat the dump. But I remove direct assignment of data to result table as this is risky, as we could have some rules applied in event on_data_change and then this would omit this rules.
I've checked with demo program 08 and everything works fine. If I have NUMC field then on selection screen you cannot enter anything than numbers, the same for decimals and integer. Maybe this occurs only on older systems?
Cheers
Łukasz

**Comment by SantiMorenoSAP** [comment]
It seems this is only for older system.



2017-02-27 21:23 GMT+01:00 Łukasz Pęgiel <notifications@github.com>:

**Comment by fidley** [comment]
Ok, I'll see if I can test it on some lower system. I guess my 7.31 on windows should still work. I'll keep you informed.

**Comment by fidley** [comment]
Santi, 
I've finally did a tests on 7.30 SP12 and using ZDEMO_FALV13 everything was working fine for NUMC fields. I was updating SPFLI-CONNID. Sorry but I cannot repeat it anyhow.

**Comment by fidley** [comment]
Falv for 7.31 is in separate repository now.
