### ISSUE TITLE
Save data from Editable ALV

### ISSUE THREAD

**Issue by luissismeiro** [fidley/falv#39]
Hi  Łukasz,

Great job on making this development and by making it available for the community!

I have a question, after we use the editable ALV, how can we save changes made by an user? 

Best Regards,
Luís

**Comment by fidley** [comment]
Thanks Luís, once you're in edit mode and you register edit event (enter or modify) then the data is directly saved to internal table after the event was fired. For example when you press enter or switch cell (depands on the event used). In this area FALV works exactly as CL_GUI_ALV_GRID.
