### ISSUE TITLE
FALV for 7.3x and 7.4x are not in sync

### ISSUE THREAD

**Issue by aztech** [fidley/falv#40]
Due to system patch level I had to use for one customer version 7.3x of your awesome class and just realised that ported version is not in sync with main one. Would it be possible, in near future, to upgrade version 7.3x to be in sync with 7.4? I see there is a lot of cool features missing like missing top of page event handling, missing export to Excel, etc.

**Comment by fidley** [comment]
I know it's unsynchronized but there problem is to find a time or person who will be able to do all of this changes. Originally if was done by Santi Moreno but as my 7.31 is crashed at the moment then I didn't sync the latter changes. Currently the 7.4 version is quite stable. Haven't found any issues so far with it, to be honest working without 7.4 at least SP5 is a pain for me. 

Let's keep it open maybe there will be someone ready to help in this synchronization, but from my side I haven't planned this from the beginning.

**Comment by aztech** [comment]
I'm trying to apply all the changes manually basing on .abap files from CODE folder.
I can share the final result but I never used Git 4 ABAP therefore I've no idea how to update repository.

**Comment by fidley** [comment]
To do it with GitHub we would need to create new repository for version 7.31 and then it's very easy once you install abapgit. There problem is that too update repository directly from you SAP system you would need to have the connection / certificates installed. But there's also an offline mode where you can export changes from your system into zip file and then you can upload it to GitHub. Let me check if I can find 7.31 in my company to install FALV and abapgit to create initial repository.

**Comment by aztech** [comment]
It would be great. Just let me know once you created repository for 7.31.

**Comment by fidley** [comment]
Finally I've made the repository for 7.31. Sorry it took so long.

https://github.com/fidley/falv731

**Comment by aztech** [comment]
No problem. I'm going to update repository after my Holidays.
