### ISSUE TITLE
Mass Replace Dump when inside splitter container

### ISSUE THREAD

**Issue by jani80k** [fidley/falv#42]
Program                                 SAPLZFALV
 Include                                 LZFALVU03
 Row                                     110
 Module Type                             (FUNCTION)
 Module Name                             Z_FALV_MASS_REPLACE

Field symbol has not been assigned yet.

Explanation: <out> is not assigned, because falv is called with a parent container.

**Comment by fidley** [comment]
OK thanks for reporting. Will check it.

**Comment by jani80k** [comment]
Let me know if you are having problems reproducing the issue. I can send you an example just in case.

**Comment by fidley** [comment]
I could reproduce it. Already corrected on my installation. Will publish it soon. If you want you can already update your installation manually as well.

![image](https://user-images.githubusercontent.com/7912195/28684039-349ea988-7303-11e7-864e-6e4a6a00f43c.png)

**Comment by fidley** [comment]
Done with v16

**Comment by jani80k** [comment]
Downloaded the newest version from the repository. Working fine. Thanks a lot!!

**Comment by SantiMorenoSAP** [comment]
Good job!thanks for all your effort
