### ISSUE TITLE
chain methods (in column class)

### ISSUE THREAD

**Issue by BlueTeck** [fidley/falv#45]
Hey,
thanks for this libary. It would be nice, to chain methods like this:

Instead of:
```
falv->column('NAME')->set_reptext('Name' ).
falv->column('NAME')->set_color('C110').
```

you could do:
```
falv->column('NAME')->set_reptext('Name' )->set_color('C110').
```
What do you think?

Regards,
Timo

**Comment by fidley** [comment]
Nice idea. This should be very simple :)

**Comment by BlueTeck** [comment]
@fidley so you will do it or should I make a pull request?

**Comment by fidley** [comment]
I can do it just give me few days to find half hour for that. I think the same I can do with layout.

**Comment by fidley** [comment]
@BlueTeck  done with latest commit. Please check demo program ZDEMO_FALV18

**Comment by BlueTeck** [comment]
Thanks 👍
