### ISSUE TITLE
Endless loop while redefining "display"

### ISSUE THREAD

**Issue by xczar0** [fidley/falv#47]
When you redefine "Display" method and inside of this method access "super->Display" FALV will jump into "endless loop execution".
Example below:
```
CLASS ZCL_TEST_FALV definition
  public
  inheriting from ZCL_FALV
  final.

public section.
 methods: DISPLAY redefinition.
ENDCLASS.


"Implementation:
 CLASS ZCL_TEST_FALV IMPLEMENTATION.

 METHOD DISPLAY.

    raise event event_handler_set.
    super->DISPLAY( ).

  ENDMETHOD.
ENDCLASS.
```

**Comment by fidley** [comment]
Display method calls itself recoursively, that's why it should be final. I will change the method definition.

**Comment by fidley** [comment]
display method set as final.
