### ISSUE TITLE
v731.1.0.3 - Method CREATE may not have a RETURNING parameter and an EXPORTING or CHANGING parameter at the same time.

### ISSUE THREAD

**Issue by bmaciag** [fidley/falv#49]
Hi, I'm using 731 and tried to run the v731.1.0.3, with the result:
class zcl_falv -> Method CREATE may not have a RETURNING parameter and an EXPORTING or CHANGING parameter at the same time.

Are you still maintaining the 731 releases?

**Comment by fidley** [comment]
Hi,
Unfortunately not. This version was done by Santi on a base of 7.40 version
and was not maintained by me. I think I don't have access to 7.31 at the
moment so I cannot check it.

Cheers
Łukasz

W dniu czw., 7.02.2019 o 08:03 B. Maciag <notifications@github.com>
napisał(a):

**Comment by fidley** [comment]
Version not supported  anymore
