### ISSUE TITLE
Issue in built-in screen callstack 

### ISSUE THREAD

**Issue by reuteraov** [fidley/falv#50]
In report ZDEMO_FALV15 the first FALV won't show after displaying second FALV.

I added the method `set_dummy_function_code( )` before calling pbo at the end of function module `z_falv_display`.  It works for me. 

![solution ](https://user-images.githubusercontent.com/48312601/54124034-88a9db80-4401-11e9-8493-b642cfb155aa.jpg)

**Comment by fidley** [comment]
Great, can you push this to Github?

**Comment by fidley** [comment]
#51
