### ISSUE TITLE
Sorting Problem

### ISSUE THREAD

**Issue by jani80k** [fidley/falv#52]
Not sure if this is a bug or not, so please close this in case I am wrong. please consider this more a question.
When sorting EKPO entries in SE16N by EBELN, only one document number is showing and the remaining entries for that document are blank.
I tried the same with FALV but it is not working, whichever way I do it.
![FALV_Sort](https://user-images.githubusercontent.com/16916879/56345518-3a39ea80-61c0-11e9-88ca-b221a49b35a2.png)

Here is what I expect:
![image](https://user-images.githubusercontent.com/16916879/56345611-6d7c7980-61c0-11e9-8ebf-9c3f08f39e63.png)

I tried everything I could find on the web by adding sorts as:

- group = 'UL'/'*'
- UP='X' 
- etc.

![image](https://user-images.githubusercontent.com/16916879/56345734-c21ff480-61c0-11e9-99ba-074d0acfc4f3.png)

...but no success.
Could you say whether this is possible or not with FALV?

Thanks in advance for your reply. I really like FALV and use it a lot. Sorry, in case this is not a bug but my mistake or an SAP Standard issue. ;)

**Comment by fidley** [comment]
Hi @jani80k ,

I think this is standard behavior when you use HOTSPOT in one of the columns. Try to remove all hotspots and then it should work. Also be sure that SET_NO_MERGING is not set to True in Layout.

Cheers
Łukasz

**Comment by fidley** [comment]
Also when grid is editable the merging of the column values does not work.

**Comment by jani80k** [comment]
Yes, you are right, Lukasz.
It is SAP Standard behaviour.
Thanks a lot...
