### ISSUE TITLE
Adaptation latest source for ABAP 702/710

### ISSUE THREAD

**Issue by Aleksoid1978** [fidley/falv#54]
Adaptation latest source for ABAP 702/710.

Currently i install **ZFALV_V731.1.0.3.nugg** from https://abapblog.com/falv
But want to use latest version from github.

It's possible ?

**Comment by fidley** [comment]
There is a second repository for that version (Fast ALV for older systems https://github.com/fidley/falv731 )

But I think it's the same version as you have. Normally I have not updated it as to be honest I'm too lazy to keep both versions equal.
