### ISSUE TITLE
Search Button in toolbar

### ISSUE THREAD

**Issue by OberstVonGatow** [fidley/falv#57]
Hi Łukasz,

i was wondering why the search button is excludet in zcl_falv_dynamic_status.
If i delete the excludet entries the buttons are available but no action gets triggert.
Couldn`t i use the standard ALV Search function with your FALV?

P.S.: Great Work! I really like the whole FALV implementation 👍

**Comment by fidley** [comment]
Hello Oberst, 

thanks for kind words.

To be honest I don't remember why it was removed. I think because the normally it didn't work with ALV grid but you needed to use the ALV function. But it should not be an issue to implement this. 

I will check in a second :)

**Comment by fidley** [comment]
OK, it is now included in standard behaviour. Please check ZDEMO_FALV01 after upgrade of the classes

**Comment by OberstVonGatow** [comment]
Wow your response time is amazing 👍
Issue is fixed.
Thank you!

Regards
Fabian
