### ISSUE TITLE
Installing FALV into systems w/o SAPlink or abapGIT

### ISSUE THREAD

**Issue by Rino53** [fidley/falv#60]
Hello There,
Recently i did installed FALV into system that does not support any 'import objects' software (and it is not possible to install any).
That was hard but doable. But i did not create proper GUI statuses for dynamic buttons feature.
So my question - is it possible to create some instruction/describing pictures how to manually create ALL the objects for FALV.

**Comment by fidley** [comment]
Just a small question, I know you wrote that you can't install abapGIT, but when you can create temp report from using the standalone abapGit ->https://docs.abapgit.org/guide-install.html then you can download the FALV repository  from Gitghub as zip.
![image](https://user-images.githubusercontent.com/7912195/100235010-26be3c00-2f2c-11eb-8828-adf084e2b7da.png)

And use abapGit in oflline mode to create the FALV package :)
![image](https://user-images.githubusercontent.com/7912195/100235138-4e150900-2f2c-11eb-9a9a-4d7eefeef695.png)

Would that be a solution?

**Comment by Rino53** [comment]
I tried to launch abapgit_standalone with no luck.
After i get error from seo_interface i thought that it's something with internet connection problem and stopeed to dig further.
![image](https://user-images.githubusercontent.com/1096551/100237600-f63cc900-2f50-11eb-9798-e1d1b86d7ea9.png)
But now i realised that the problem is coming when program tries to create interface ZIF_APACK*.
![image](https://user-images.githubusercontent.com/1096551/100237942-68151280-2f51-11eb-9601-df2692c410c4.png)
I will modify name of ZIF_APACK* in source with something that is matches allowed prefix convention and try abapgit again.

**Comment by larshp** [comment]
hmm, check the `SY` variables to check if there is a better error message

does the $TMP package exist in the system, plus do you have a developer key on the system/client?

**Comment by fidley** [comment]
I could believe it is naming convention. I have similar settings on one of the systems, that standard developers are not allowed to create the objects outside the naming convention and sadly ZIF_ is not correct name for interface there.  But as I am not standard developer, I could do this without issues. 

But it is better to check the message as you said Lars.

**Comment by Rino53** [comment]
it is 100% naming convention.

**Comment by larshp** [comment]
but you have access to create falv objects manually? do you get an error when trying manually to create the interface?

**Comment by Rino53** [comment]
i did renamed all objects with allowed prefix when i created falv manually. It is known restriction in the system.

**Comment by larshp** [comment]
oh, okay 👍

**Comment by Rino53** [comment]
Horay! After renaming ZIF_APACK_INTERFACE, abap_git is able to run on system.
But i still have some questions:
1. How can i contribute in abapgit_standalone source code, located at https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap? I want to propose some changes that helped me.
2. Still, i think, if i try to to install FALV with abapgit - i suppose it will fail (because of objects prefixes), right? So the best way is manualy find/replace names in source xml?

**Comment by fidley** [comment]
You can contribute here https://github.com/abapGit/abapGit. You can also fork it and prepare own version for crazy systems.

But in case of dynamic programming, you will have the troubles. Like in FALV for the buttons in GUI.  So search through the xml and abap files would be needed with replacement.

**Comment by mbtools** [comment]
FALV doesn't use APACK. The issue is with abapGit generating the ZIF interface... Yet another reason to find a replacement for APACK (working on it)

**Comment by fidley** [comment]
An perfect solution for the abapGit and such system would be possibility to give the parameters for replacing the names or prefixes for the names. It could work with simple replace all occurences. But It would needed to do adaptations not only in the XML files but also in ABAP files.
