### ISSUE TITLE
program errors in S/4 Hana 2020

### ISSUE THREAD

**Issue by jani80k** [fidley/falv#64]
Hi,
on 
S4CORE	105	0000
SAP_ABA	75F	0000	-

I get this error on all the example programs whenever "add_button" is used.

Program errors

Message no. 0K534

Diagnosis

A common cause is that the output table passed to the ALV is not defined globally but locally. Thus, the reference to the table is lost. The ALV no longer has an output table.

Procedure

Define the output table globally.

**Comment by fidley** [comment]
Hi, 
have you had problems on other releases? So far this was working without issues? Probably I will not have an access to S/4 2020 until mid year :( 

Cheers
Łukasz

**Comment by jani80k** [comment]
I will do some more investigation tomorrow but this clearly seems to come from SAP standard..
Maybe I find out some more details... the error message seems misleading- if I google it it is years old...

**Comment by fidley** [comment]
thanks, normally this error was appearing when you used a private table to display in grid that was editable as far as I remember.

**Comment by jani80k** [comment]
![alvgrid issue](https://user-images.githubusercontent.com/16916879/106745450-69358080-6621-11eb-873b-11ce3fd9689f.png)
This is where it goes wrong, e.g. in ZDEMO_FALV08 latest version on first add_button method call.

**Comment by jani80k** [comment]
The difference between the system where it is working and the system where I am getting the error is this:
![grafik](https://user-images.githubusercontent.com/16916879/106749064-5bcec500-6626-11eb-90be-887501119359.png)
In the debugger for some strange reason with F5 the system does not go inside the method me->set_toolbar_interactive but throws an exception.
On my new S/4 Hana Box, F5 goes inside that method and causes the issue.
The class that contains this method is CL_GUI_ALV_GRID on both systems.

**Comment by fidley** [comment]
Really strange, as there is catch of CX_ROOT then the exception should be handled. I just tried in my "older" sandboxes and it works like that. In your case it is not catched?

**Comment by jani80k** [comment]
No, if I press F5 in the debugger, it behaves like F6  and an exception is raised.
In the S/4 System F5 behaves normally and at some point a message is raised.

**Comment by fidley** [comment]
Try replacing the code of refresh_toolbar method with this one. It should avoid calling the toolbar objects before first display happens.

```
  method refresh_toolbar.
    check cl_gui_alv_grid=>offline( ) is initial.
    check grid->m_init_toolbar eq space.
    try.
        me->set_toolbar_interactive(  ).
      catch cx_root.
        "in case method is called before the display of grid
        "no need to do anything with that
        clear sy-subrc.
    endtry.
    r_falv = me.
  endmethod.
```

**Comment by jani80k** [comment]
It seems ok, now. Thanks!
Should I check for any side effects?

**Comment by fidley** [comment]
I assume there is none, but you could check of course. I did some checks on older releases and I had no issues. That is why I will commit this change soon.

**Comment by jani80k** [comment]
Cool, thx.
