### ISSUE TITLE
F4 help not working for tables defined using local structures (TYPES: BEGIN OF ..)

### ISSUE THREAD

**Issue by riscutiatudor** [fidley/falv#65]
If you create the FALV using a locally defined structure (TYPES: BEGIN OF ...) and use a data element which has a search help assignment, the cell displays the icon that F4 help is available but when pressing it, nothing happens. The reason for this is that fields REF_TABLE and REF_FIELD of the field catalog are empty.
There are (at least) two options to fix this:
1. Look for a database table where this data element is used and manually set the values (REF_TABLE and REF_FIELD) of the field catalog. A simple way to achieve this is to call the GET_BACKEND_FIELDCATALOG and SET_FRONTEND_FIELDCATALOG methods.
2. (Proposed by Lukasz himself): If REF_TABLE and REF_FIELD are empty, but the ROLLNAME is not initial and F4AVAILABLE = X, then check which search help is assigned to the data element and call the F4IF_GET_SHLP_DESCR and F4IF_START_VALUE_REQUEST function modules.

**Comment by fidley** [comment]
It's been a while.... but maybe you want to test it?

Branch [automatic_f4_and_col_pos_update](https://github.com/fidley/falv/tree/automatic_f4_and_col_pos_update)
