### ISSUE TITLE
Column position

### ISSUE THREAD

**Issue by xavipuga** [fidley/falv#66]
Hello,

I'm just starting to use your FALV classes and it's an incredible work. Congratulations and thanks for share.

I'm strugling to set columns position on my editable alv on 740 system.

This is the fieldcatalog before setting up the order:
![image](https://user-images.githubusercontent.com/9490777/120794278-474cfb80-c538-11eb-9892-7a461fa3286f.png)

my set_col_pos call:

```
METHOD set_columns_order.

    DATA lo_column TYPE REF TO zcl_falv_column.
    DATA ld_index TYPE i.
    lo_column = go_alv->column( 'STAT'  )->set_col_pos( 1 ).
    lo_column = go_alv->column( 'MATNR'  )->set_col_pos( 2 ).
    lo_column = go_alv->column( 'MAKTX'  )->set_col_pos( 3 ).

  ENDMETHOD. "set_columns_order.
```

And this is the resultant fieldcatalog:
![image](https://user-images.githubusercontent.com/9490777/120794525-a3b01b00-c538-11eb-8f24-3f43cecda529.png)

It's that an issue? Or my mistake with the call?

Thanks a lot.

**Comment by fidley** [comment]
Hi @xavipuga, 

I will check that, but it is strange that it works this way. I will run your code on my installation and I'll come back to you.

Cheers
Łukasz

**Comment by fidley** [comment]
It's been a while, but maybe you want to test the solution?
Branch [automatic_f4_and_col_pos_update](https://github.com/fidley/falv/tree/automatic_f4_and_col_pos_update)

**Comment by fidley** [comment]
#88
