### ISSUE TITLE
Syntax error in class zcl_falv in S4 2021 Feature Pack 1

### ISSUE THREAD

**Issue by kershub** [fidley/falv#69]
Hi FALV-Team,

our company is now convert the ECC System to the S4/Hana System and now on a converted Sandbox.
Release: SAP_BASIS	756	0001	SAPK-75601INSAPBASIS	SAP-Basiskomponente

The class ZCL_FALV has a syntax error in line 1694
Error Message:
Method CREATE_EX_RESULT_FALV
Casts between two incompatible references (to the types "CL_SALV_TABLE"
and "CL_SALV_MODEL") do not work. This kind of cast always produces a
runtime error.

Can you please help me

Best regards

**Comment by fidley** [comment]
Hello,
I also have this issue on the newest release. Seems SAP has changed the SALV classes and the way they prepare export to excel from it. Quick fix would be to comment the method if you're not using the Falv export to excel method.

For the replacement, we need to figure out how to correct this, so it works in all releases.

**Comment by fidley** [comment]
@kershub it should be solved with latest version
