### ISSUE TITLE
Empty screen with simple FALV creation

### ISSUE THREAD

**Issue by sydea-viannaccone** [fidley/falv#71]
Hi. 
I installed FALV manually (abapgit nor working properly), and after some tries i managed to activate all objects.
The strange fact is i have an empty screen when i go display.

I created a 0100 screen into fgroup where ZFALV_DISPLAY fm is and i supposed a standard container would be constructed dinamically.
![image](https://user-images.githubusercontent.com/71014283/176460306-4986c727-4011-4f65-9019-bcf3fda805f1.png)

It's like a container hasn't been set...
I'm doing this as the easiest test i could:
![image](https://user-images.githubusercontent.com/71014283/176460731-25936cc6-feac-4b77-b4f0-1b6b65fb6e44.png)

Am I doing something wrong?

Tnx in advance!

**Comment by fidley** [comment]
Hello, 
no, the custom container needs to be created inside. Anyway maybe firstly update abapGit and the try again?

Cheers
Łukasz
