### ISSUE TITLE
Syntax error in program "ZCL_FALV_COLUMN===============CP        ".

### ISSUE THREAD

**Issue by Nioniotte** [fidley/falv#83]
Hello,

When I run, the program ZDEMO_FALV01 or other demo, I have this dump:

 Error in the ABAP application program.

 The current ABAP program "ZCL_FALV======================CP" had to be
  terminated because it found a
 statement that could not be executed.
 In include "ZCL_FALV_COLUMN===============CM03U     ", in line 15 of program
  "ZCL_FALV_COLUMN===============CP        ", the following syntax errors
 have occurred:
 **Le type 'FIXVALUES' est inconnu.**

In ZCL_FALV_COLUMN, method SET_DRDN_HNDL: lt_fixed_values     TYPE cl_abap_elemdescr=>fixvalues 

But fixvalues is not exist in class cl_abap_elemdescr. 

I'm in SAP SAP_ABA 750 SP 0023.

Misha

**Comment by fidley** [comment]
Hello Misha, 
could you update the method to use type DDFIXVALUES there and see if this works?
According to comments it should be compatible with  cl_abap_elemdescr=>fixvalues.

Cheers
Łukasz

**Comment by Nioniotte** [comment]
I changed the line
          ,lt_fixed_values     TYPE cl_abap_elemdescr=>fixvalues
by:
          ,lt_fixed_values     TYPE STANDARD TABLE OF ddfixvalue WITH EMPTY KEY

Now it work

**Comment by fidley** [comment]
Are you able to make pull request with your changes?

**Comment by Nioniotte** [comment]
> Are you able to make pull request with your changes?

I never do that. But I will try it...

**Comment by Nioniotte** [comment]
> > Are you able to make pull request with your changes?
> 
> I never do that. But I will try it...

I try to login from SAP but I get the error : Unauthorized access to resource (HTTP 401). Check your credentials.

My credentials are correct. :-/

**Comment by fidley** [comment]
Thanks!
