### ISSUE TITLE
Missing options in pop-up "Change Layout"

### ISSUE THREAD

**Issue by Nioniotte** [fidley/falv#90]
Hello,

On ALV display:

If I click the button Change Layout... (CTRL+F8), I have only the tab "Column Selection" and "Display".

When I change directly in list, for exemple sorting a column, and after that I click on the button Change Layout, I have the tab "Column Selection", "Sort Order", "Filter", "View" and "Display".

It is an issue or I need to add a parameter when calling falv?

Best regards,
Misha

**Comment by fidley** [comment]
Hi Misha, 
sorry for not answering directly but I forgot. 
Normally this is the first time I see the difference between calling FALV with GUI toolbar usage, and FALV with internal toolbar usage.
In ZDEMO_FALV13 when using GUI toolbar                                               
![image](https://github.com/fidley/falv/assets/7912195/51dc7429-c5a1-479f-b9a3-6f10b5345ea7)

when using ALV grid toolbar.
![image](https://github.com/fidley/falv/assets/7912195/8a0477cb-9421-4a0e-9634-08a9db186312)

I've debug a bit and seems this is not a bug, but a feature...of SAP. When there is no ALV grid toolbar, then some of the tabs are hidden.
![image](https://github.com/fidley/falv/assets/7912195/07f6610a-27f0-4cff-9ec8-c08ca3745c6b)

**Comment by Nioniotte** [comment]
ok strange. Thank you

**Comment by fidley** [comment]
Standard SAP Behaviour
