### ISSUE TITLE
Missed r_falv value at method exclude_function

### ISSUE THREAD

**Issue by igdies** [fidley/falv#91]
Hi,
I missed this at method  exclude_function :-)
`r_falv = me.`

https://github.com/fidley/falv/blame/6aabc94ab35fc0435eba4eca5772f5c650bf049c/CODE/zcl_falv.clas.abap#L1524

**Comment by larshp** [comment]
suggest just opening a pull request with the fix?

**Comment by fidley** [comment]
Hi @igdies ,
A pull request would be great!

**Comment by igdies** [comment]
I'll try it!! 
I am quite new at GitHub

**Comment by fidley** [comment]
1.Fork the repository to your github account
2. Clone it with abapGit to your abap system
3. update the code
4. Push changes to your repository
5. create pull request to this one :)

More or less ;)

**Comment by larshp** [comment]
or just the edit button, https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files, its a small change. 

For larger changes, do as @fidley suggests

**Comment by igdies** [comment]
> or just the edit button, https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files, its a small change.
> 
> For larger changes, do as @fidley suggests

I'd say it is done.

**Comment by fidley** [comment]
Thanks!
