### ISSUE TITLE
Encapsulate table type inside class

### ISSUE THREAD

**Issue by wolfsolver** [fidley/falv#95]
Many times I use falv with internal type structure. I didn't find any way to this in a simply way. 
My main goal is to have a class that define internal type and that act al single block. Main issue in this is that both create and createbnyref require that type is know exteraly from method. 

A way to solve this is to have:

1. A public method that create empty data and a method for run
```
  PUBLIC SECTION.
    class-METHODS create_empty RETURNING value(rv_falv) TYPE REF TO ZCL_FALV.
    METHODS run.
```
2. have internal type inside private section
```
  PRIVATE SECTION.
  types: BEGIN OF ty,
    " your data type here
    END OF ty.
  types tyt type TABLE OF ty.
  data: mt type tyt.
```
3. have a run method that select data and perform display
```4  METHOD run.
   METHOD run.
   " your stuff to read data into table
   select  * into table mt from ...
    set_output_table( CHANGING ct_table = mt ).
    me->display(   ).
  ENDMETHOD.
```
4. main program is simply, no data type..
```
data lc_mccode type ref to lcl_popup.
lc_mccode ?= lcl_popup=>create_empty( ).
lc_mccode->run( ).
```

My suggestion is to have this method directly into ZCL_FALV

**Comment by fidley** [comment]
Hi @wolfsolver , 
not sure if I get it correctly. As I also use internal type very often, I don' have any issues with using a table build on a base of such type in CREATE method.  Have you found any restrictions?
Or its just that you would like to have one class to select data, keep types and display it as well?

**Comment by wolfsolver** [comment]
Hi! after your comment, i made a test, that i didn't do befor (a I didn't suppose to work).

Simply define type in public section and reference in create_by_Ref work

```
CLASS lcl_test DEFINITION INHERITING FROM zcl_falv.
  PUBLIC SECTION.
    TYPES: BEGIN OF TY_SFLIGHT.
             INCLUDE type sflight.
    TYPES:   styles TYPE lvc_t_styl,
           END OF TY_SFLIGHT.
    types: TY_T_SFLIGHT TYPE STANDARD TABLE OF TY_SFLIGHT.
    METHODs load_data.
    
  PRIVATE SECTION.
    DATA: sflights TYPE TY_T_SFLIGHT.
```

and using
`falv ?= lcl_test=>create_by_type( i_type = cl_abap_typedescr=>describe_by_name( 'LCL_TEST=>TY_T_SFLIGHT' ) ).`

work fine.
